document.addEventListener("DOMContentLoaded",()=>{const $=id=>document.getElementById(id);
const USERS=[{email:"demo@agroinventario.cl",password:"NIDA2026",name:"Renato",workspace:"AgroInventario",plan:"Piloto activo"},{email:"demo@nida.cl",password:"NIDA2026",name:"Daffne",workspace:"NIDA Technology",plan:"Administrador"}];
const STORAGE="nida_records_v4",SESSION="nida_session_v4";let user=null,current=null,companies=[],fields=[];
const views={dashboard:["Inicio","Gestiona registros desde un solo lugar."],visit:["Nueva visita","Captura la información mientras aún está fresca."],history:["Historial","Consulta los registros confirmados."]};
function esc(v=""){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{"Content-Type":"application/json",...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||("HTTP "+r.status));return d}
function nav(id){document.querySelectorAll(".view").forEach(x=>x.classList.add("hidden"));$(id).classList.remove("hidden");document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.view===id));$("pageTitle").textContent=views[id][0];$("pageSubtitle").textContent=views[id][1];if(id==="dashboard")stats();if(id==="history")history()}
document.querySelectorAll(".nav").forEach(x=>x.onclick=()=>nav(x.dataset.view));$("goVisitBtn").onclick=()=>nav("visit");
function login(){const e=$("email").value.trim().toLowerCase(),p=$("password").value;const f=USERS.find(x=>x.email===e&&x.password===p);if(!f){$("loginError").classList.remove("hidden");return}user=f;sessionStorage.setItem(SESSION,JSON.stringify(f));$("loginError").classList.add("hidden");show()}
function show(){if(!user)return;$("loginScreen").classList.add("hidden");$("appScreen").classList.remove("hidden");$("workspaceName").textContent=user.workspace;$("workspacePlan").textContent=user.plan;$("userName").textContent=user.name;$("userEmail").textContent=user.email;$("welcomeTitle").textContent=user.workspace+", tu espacio NIDA está listo.";nav("dashboard");status();loadCompanies()}
$("loginBtn").onclick=login;$("password").onkeydown=e=>{if(e.key==="Enter")login()};$("logoutBtn").onclick=()=>{sessionStorage.removeItem(SESSION);location.reload()};
try{const s=sessionStorage.getItem(SESSION);if(s){user=JSON.parse(s);show()}}catch{}
function setStatus(t,d,x){t.textContent=x?.message||"No disponible";d.className="dot "+(x?.connected?"connected":"pending")}
async function status(){try{const d=await api("/api/integrations/status");setStatus($("notionStatusText"),$("notionStatusDot"),d.notion);setStatus($("githubStatusText"),$("githubStatusDot"),d.github)}catch(e){$("notionStatusText").textContent="Servidor no disponible";$("githubStatusText").textContent="Servidor no disponible"}}
$("refreshStatusBtn").onclick=status;
async function loadCompanies(){const s=$("clientInput");s.disabled=true;s.innerHTML='<option value="">Cargando empresas…</option>';try{const d=await api("/api/notion/companies");companies=d.items||[];s.innerHTML='<option value="">Selecciona una empresa</option>'+companies.map(x=>'<option value="'+esc(x.id)+'">'+esc(x.name)+'</option>').join("");s.disabled=false}catch(e){s.innerHTML='<option>No se pudieron cargar empresas</option>'}}
async function loadFields(id){const s=$("locationInput");s.disabled=true;s.innerHTML='<option value="">Cargando campos…</option>';if(!id){s.innerHTML='<option value="">Selecciona primero una empresa</option>';return}try{const d=await api("/api/notion/fields?companyId="+encodeURIComponent(id));fields=d.items||[];s.innerHTML='<option value="">Selecciona un campo / proyecto</option>'+fields.map(x=>'<option value="'+esc(x.id)+'">'+esc(x.name)+'</option>').join("");s.disabled=false}catch(e){s.innerHTML='<option>No se pudieron cargar campos</option>'}}
$("clientInput").onchange=e=>loadFields(e.target.value);
function text(sel){return sel.options[sel.selectedIndex]?.textContent?.trim()||""}
function norm(s=""){return s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()}
function sentences(s=""){return s.split(/(?<=[.!?])\s+|\n+/).map(x=>x.trim()).filter(Boolean)}
function matching(s,keys,f="Por confirmar"){const a=sentences(s).filter(x=>keys.some(k=>norm(x).includes(norm(k))));return a.join("\n")||f}
function first(s,keys){return sentences(s).find(x=>keys.some(k=>norm(x).includes(norm(k))))||""}
function type(s){const n=norm(s);if(n.includes("implement"))return"Implementación";if(n.includes("capacit"))return"Capacitación";if(n.includes("seguimiento"))return"Seguimiento";if(n.includes("reunion"))return"Reunión";return"Visita a terreno"}
function github(s){const n=norm(s);return["error","falla","incidencia","bug","no funciona","no permite","no deja","problema del sistema"].some(k=>n.includes(k))}
function section(s){const a=["módulo de inventario","inventario","guía de despacho","reportes","facturación","usuarios","configuración"];const n=norm(s);return a.find(x=>n.includes(norm(x)))||"Por confirmar"}
function nextDate(s){const n=norm(s);for(const d of["lunes","martes","miercoles","jueves","viernes","sabado","domingo"])if(n.includes(d))return d.charAt(0).toUpperCase()+d.slice(1);const m=s.match(/\b(\d{1,2}[\/-]\d{1,2}(?:[\/-]\d{2,4})?)\b/);return m?m[1]:"Por confirmar"}
function today(){const d=new Date();return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")}
$("exampleBtn").onclick=async()=>{if(!companies.length)await loadCompanies();if(companies[0]){$("clientInput").value=companies[0].id;await loadFields(companies[0].id);if(fields[0])$("locationInput").value=fields[0].id}$("reportInput").value="Hoy realizamos una visita de seguimiento. Revisamos el módulo de inventario y explicamos cómo registrar una guía de despacho. El cliente solicitó mejorar los reportes. Nosotros quedamos de revisar la solicitud. El cliente enviará capturas. Detectamos un error al guardar una guía de despacho. Quedó pendiente revisar la incidencia con TI y nos reuniremos nuevamente el viernes."};
$("processBtn").onclick=()=>{const companyId=$("clientInput").value,fieldId=$("locationInput").value,client=text($("clientInput")),location=text($("locationInput")),report=$("reportInput").value.trim();if(!companyId)return alert("Selecciona una empresa.");if(!fieldId)return alert("Selecciona un campo o proyecto.");if(!report)return alert("Escribe o dicta el reporte.");const g=github(report);current={id:Date.now(),workspace:user.workspace,companyId,fieldId,client,location,type:type(report),visitDate:today(),reviewed:matching(report,["revisamos","vimos","analizamos","explicamos","capacitamos","configuramos","mostramos"]),requests:matching(report,["cliente solicit","cliente pidió","cliente pidio","nos solicitaron","nos pidieron","requiere"],"Sin solicitudes adicionales detectadas."),teamCommitments:matching(report,["nosotros quedamos","quedamos de","vamos a revisar","vamos a validar","debemos revisar"]),clientCommitments:matching(report,["cliente quedó","cliente quedo","cliente debe","cliente enviará","cliente enviara"]),explanation:matching(report,["explicamos","paso a paso","mostramos","capacitamos","indicamos"]),nextSteps:matching(report,["nos reuniremos","próxima","proxima","siguiente","volveremos","seguimiento"]),followup:matching(report,["pendiente","revisar","validar","confirmar","falta","queda por"]),nextDate:nextDate(report),github:g,githubSection:g?section(report):"",githubPriority:"",githubProblem:g?(first(report,["error","falla","incidencia","problema"])||"Por confirmar"):"",githubSteps:g?matching(report,["al intentar","al presionar","después de","despues de","cuando","guardar"]):"",githubContext:g?report:"",reportOriginal:report,createdAt:new Date().toLocaleString("es-CL")};fill()};
function fill(){const r=current;["Client","Location","Type","VisitDate","Reviewed","Requests","TeamCommitments","ClientCommitments","Explanation","NextSteps","Followup","NextDate"].forEach(k=>$("result"+k).value=r[k.charAt(0).toLowerCase()+k.slice(1)]||"");$("resultGithub").value=String(r.github);$("githubSection").value=r.githubSection;$("githubPriority").value=r.githubPriority;$("githubProblem").value=r.githubProblem;$("githubSteps").value=r.githubSteps;$("githubContext").value=r.githubContext;$("githubDraft").classList.toggle("hidden",!r.github);$("resultCard").classList.remove("hidden");$("resultCard").scrollIntoView({behavior:"smooth"})}
$("resultGithub").onchange=e=>$("githubDraft").classList.toggle("hidden",e.target.value!=="true");
$("cancelBtn").onclick=()=>{$("resultCard").classList.add("hidden");current=null};
function edited(){return{...current,client:$("resultClient").value.trim(),location:$("resultLocation").value.trim(),type:$("resultType").value.trim(),visitDate:$("resultVisitDate").value,reviewed:$("resultReviewed").value.trim(),requests:$("resultRequests").value.trim(),teamCommitments:$("resultTeamCommitments").value.trim(),clientCommitments:$("resultClientCommitments").value.trim(),explanation:$("resultExplanation").value.trim(),nextSteps:$("resultNextSteps").value.trim(),followup:$("resultFollowup").value.trim(),nextDate:$("resultNextDate").value.trim(),github:$("resultGithub").value==="true",githubSection:$("githubSection").value.trim(),githubPriority:$("githubPriority").value,githubProblem:$("githubProblem").value.trim(),githubSteps:$("githubSteps").value.trim(),githubContext:$("githubContext").value.trim(),createdAt:new Date().toLocaleString("es-CL")}}
function all(){try{const x=JSON.parse(localStorage.getItem(STORAGE)||"[]");return Array.isArray(x)?x:[]}catch{return[]}}
function mine(){return all().filter(x=>x.workspace===user?.workspace)}
$("confirmBtn").onclick=async()=>{if(!current)return;const b=$("confirmBtn"),old=b.textContent,r=edited();b.disabled=true;b.textContent="Guardando…";let remote=null,err=null;try{remote=await api("/api/visits",{method:"POST",body:JSON.stringify(r)})}catch(e){err=e}finally{const a=all();r.remote=remote||{ok:false,error:err?.message};a.unshift(r);localStorage.setItem(STORAGE,JSON.stringify(a));$("clientInput").value="";$("locationInput").innerHTML='<option value="">Selecciona primero una empresa</option>';$("locationInput").disabled=true;$("reportInput").value="";$("resultCard").classList.add("hidden");current=null;b.disabled=false;b.textContent=old;stats();status();alert(err?"⚠️ Se guardó copia local. Integración: "+err.message:(remote?.notion?.saved||remote?.github?.created?"✅ Guardado. Integraciones ejecutadas.":"✅ Guardado en modo demo."));nav("history")}};
function stats(){const a=mine();$("statRecords").textContent=a.length;$("statIssues").textContent=a.filter(x=>x.github).length;$("statLast").textContent=a[0]?.createdAt||"Sin registros"}
function history(){const a=mine(),c=$("historyContainer");if(!a.length){c.innerHTML='<div class="empty">Sin registros todavía.</div>';return}c.innerHTML=a.map(r=>'<article class="history-item"><div class="row"><strong>'+esc(r.client)+' · '+esc(r.location)+'</strong><span>'+esc(r.type)+'</span></div><p>'+esc(r.createdAt)+'</p><p><b>Solicitudes:</b> '+esc(r.requests||"Por confirmar")+'</p><p><b>Seguimiento:</b> '+esc(r.followup||"Por confirmar")+'</p>'+(r.github?'<span>⚠ Requiere revisión técnica</span>':'')+'</article>').join("")}
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;let rec,listening=false;if(SR){rec=new SR();rec.lang="es-CL";rec.continuous=true;rec.interimResults=false;rec.onstart=()=>{listening=true;$("voiceBtn").textContent="⏹ Detener";$("voiceStatus").textContent="Escuchando…"};rec.onend=()=>{listening=false;$("voiceBtn").textContent="🎙 Dictar";$("voiceStatus").textContent="Dictado finalizado."};rec.onresult=e=>{let t="";for(let i=e.resultIndex;i<e.results.length;i++)if(e.results[i].isFinal)t+=e.results[i][0].transcript+" ";if(t)$("reportInput").value+=($("reportInput").value?" ":"")+t.trim()};$("voiceBtn").onclick=()=>listening?rec.stop():rec.start()}else{$("voiceBtn").disabled=true;$("voiceStatus").textContent="Dictado no disponible en este navegador."}
});